<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="NewsSortList.aspx.cs" Inherits="News.NewsSortList" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        .div1{
            margin-top:20px;
            margin-left:20px;
            float:left;
            margin-right:20px;
        }
        #NewsSort{
            text-decoration:none;
            padding:10px;
            border:1px solid RGB(22,155,213);
            font-size:15px;
            background-color:RGB(22,155,213);
            border-radius:8px;
            color:white;
            padding-bottom:15px;
            padding-top:15px;
        }
        .div2{
            margin-top:30px;
        }
        .gvSort{
            text-align:center;
            padding:5px;
            margin-left:20px;
            margin-top:10px;
            width:800px;
            font-size:25px;
            text-decoration:none;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="div1"><span>新闻分类列表</span></div>
    <div class="div2"><a id="NewsSort" href="NewsSortEdit.aspx">添加新闻分类</a></div>
    <br />
    <asp:GridView ID="gvNewSort" CssClass="gvSort" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing">
        <Columns>
            <asp:BoundField DataField="ID" HeaderText="新闻分类ID" />
            <asp:BoundField DataField="NewsSortName" HeaderText="新闻分类名称" />
            <asp:BoundField DataField="CreatedTime" HeaderText="创建时间" />
        </Columns>
    </asp:GridView>
    <br />
</asp:Content>
